.travis.yml
appveyor.yml

Extended Travis integration and added AppVeyor integration

---

Cargo.toml
src/demuxer.rs
src/ebml.rs
src/elements.rs
src/lib.rs
src/permutation.rs
src/serializer/ebml.rs

nom5 support

---

src/muxer.rs

fix track number

---

src/demuxer.rs
src/ebml.rs
src/elements.rs
src/lib.rs
src/permutation.rs

fmt and clean

---

tools/src/matroska_info.rs

more output in matroska info

---

src/ebml.rs

fix type cast in wi686

---

src/demuxer.rs

stream id is not uid

---

Cargo.toml
examples/matroska_remux.rs

clean remux example

---

.github/workflows/matroska.yml

- Update `action-rs` actions
- Add `macOS`
The `clippy-rustfmt` failure is right, `clippy` has found some errors in the code.
Thanks in advance for your review! :)

Update Github Actions

---

src/demuxer.rs
src/ebml.rs
src/elements.rs
src/lib.rs
src/serializer/ebml.rs
src/serializer/elements.rs

Fixes #58. I changed the code where the warnings pointed to, unless it didn't make sense to, in that case I added an allow-attribute.

Fix clippy warnings

---

tools/Cargo.toml
tools/src/matroska_info.rs

Fix `clippy` errors and warnings for the `matroska_info` tool
Thanks in advance for your review! :)

Fix clippy errors and warnings for tools

---

src/demuxer.rs

Hi.
I'm trying to implement specific track number demuxing, because I only need the video.
Currently, the demuxer panics when it encounters audio (at least with my test file that contains E-AC-3) while reading the headers/tracks:
```
thread 'main' panicked at 'not implemented', av-data-0.2.2/src/audiosample.rs:255:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
So far the patch seems to work, however EOF is encountered prematurely when demuxing the first (video) track only.
So the demuxing ends at ~150 000 packets when I'm expecting around ~170 000.
I haven't looked yet as to why, but am still creating this as a draft to hopefully get some help or insight.

Allow selecting track numbers to demux

---

Cargo.toml
src/muxer.rs

Update `av-data` and `av-format` crates to their last version
Thanks in advance for your review! :)

Update av crates

---

.github/workflows/matroska.yml
Cargo.toml
src/demuxer.rs
src/ebml.rs
src/elements.rs
src/lib.rs
src/muxer.rs
src/serializer/ebml.rs
src/serializer/elements.rs
tools/Cargo.toml

This PR cleans up the code a bit and updates Rust edition and CI Clippy checks

Clean up code a bit

---

src/demuxer.rs
src/ebml.rs
src/elements.rs
src/muxer.rs
src/serializer/ebml.rs
src/serializer/elements.rs
tools/src/matroska_info.rs

This PR removes dead code from the crate

Remove dead code from crate

---

src/lib.rs
src/muxer.rs
src/serializer/cookie_utils.rs
src/serializer/ebml.rs
src/serializer/elements.rs
src/serializer/mod.rs

This PR removes every cookie_factory macro from the serializer making the code more readable

Remove every cookie_factory macro from serializer

---

src/demuxer.rs

This PR removes a series of `TODO` present in the demuxer code and simplifies it a bit

Improve demuxer code

---

src/demuxer.rs
src/elements.rs
src/muxer.rs

This PR simplifies  muxer code a bit

Simplify muxer code

---

tools/src/matroska_info.rs

1. Fix some small things (capitalization/wording)
2. Fix duration formatting
3. Fix segment UID formatting

Improve matroska_info output

---

src/demuxer.rs
src/ebml.rs
src/elements.rs
src/muxer.rs
src/serializer/ebml.rs

These are just some small things I wanted to improve to make our own lives easier. I wanted to get this out of the way before doing bigger changes.

Some refactoring in ebml.rs
