rust-av/matroska

Cargo.toml

https://github.com/rust-av/rust-av/issues/55

Use GIT dependencies for out-of-repository crates instead of paths

---

tools/src/matroska_info.rs

From https://github.com/rust-av/matroska/issues/12
Just a start for the issue so far-- still a bit unsure how I'm supposed to get the position for each element and why the size seems to differ from the output of mkvinfo.

[WIP] Parity with mkvinfo

---

README.md

AppVeyor isn't yet enabled for this repo, that needs to be done in the AppVeyor setting or on the [GitHub marketplace](https://github.com/marketplace/appveyor).

Add AppVeyor badge to Readme

---

Cargo.toml

This PR fixes dependency resolution with the toolchain packaged alongside newer versions of Rust (and probably has something to do with my changes in the rust-av repo). I'll update code practices and style in a separate PR, but if this passes CI it should be a rather minor upgrade to go along with my other update PRs.

Fix dependency graph prior to Rust 2018 update

---

Cargo.toml
examples/matroska_remux.rs
src/demuxer.rs
src/ebml.rs
src/elements.rs
src/lib.rs
src/muxer.rs
src/permutation.rs
src/serializer/ebml.rs
src/serializer/elements.rs
tools/src/matroska_info.rs

This PR contains fixes and stylistic changes related to Rust 2018, with a focus on making compilation possible on recent nightly releases (without warnings or errors) before tackling style-related updates.
**Todo:**

Step1: Update to Rust 2018 Edition

---

tools/Cargo.toml
tools/src/matroska_info.rs

Fixes #44.
`UnexpectedElement` and `Parse` unfortunately have to be strings due to the lifetimes associated with their sources.

replace panics in matroska_info with errors

---

Cargo.toml
src/serializer/ebml.rs
src/serializer/elements.rs

- Update `quickcheck` to 1.0
- Fix tests using only an admissible input subset for `test_seek_head` and `test_vint`
This PR closes #80

Update quickcheck to 1.0

---

src/serializer/ebml.rs
src/serializer/elements.rs

This PR returns an error for large `vint_size` numbers and refactors the tests accordingly to the changes

 Return an error for large vint_size numbers

---

src/demuxer.rs
src/ebml.rs
src/elements.rs
src/permutation.rs

This PR fixes a demuxer test applying some of the following changes:
- Fix sub elements parsing
- Introduce a new matroska permutation parser that skips void elements
- Fix wrong tracks handling in demuxer code

Fix demuxer test

---

src/elements.rs

ID is wrong and groups without reference_priority are skipped.
The wider issue though is that `matroska_permutation` ignores all errors.

BlockGroup silently ignored

---

src/elements.rs
src/muxer.rs
src/serializer/ebml.rs

Some [new clippy warnings](https://github.com/rust-av/matroska/actions/runs/4544731886/jobs/8011595533?pr=98) have come up since the last commit to master. This PR just fixes those few small things.

Fix new clippy warnings

---

src/demuxer.rs
src/ebml.rs

This is a suggestion to make the EBML errors better. Feel free to change things or just let me know what you think.
Changes:
1. Introduce `ebml::EbmlError` enum to represent errors instead of u8 error codes.
2. Change some of the error code values (the values 1 and 104 were used ambiguously)
3. Make the helper function `custom_error` return a `nom:Err` (specifically, the recoverable `Error` variant) wrapped around the `ebml::Error` instead of just the `ebml::Error`. This simplifies the function calls.
I thought about `#[repr(u8)]` for the new enum, but realistically the enclosing `ebml::Error` struct will be padded anyways, so it probably doesn't matter if the enum is represented as a u16 or even larger in the future.
I'm not sure about the actual error codes. If the numerical values are …

Replace EBML parsing error code (u8) with error enum

---

src/ebml.rs

As discovered in #76, a lot of the elements in the EBML header are effectively optional due to having a default value. This change just uses these default values instead of erroring out.

Handle optional elements in EBML Header properly

---

README.md

The Matroska spec draft seems to have been moved into the IETF [cellar WG](https://datatracker.ietf.org/wg/cellar/about/). This PR just updates the links in the PR to reflect that change.

(README) Update links to RFC/git repo

---

src/demuxer.rs
src/ebml.rs
src/elements.rs

After #101, I decided to try and improve the errors more.
The ebml error type now looks like this:
```rust
#[derive(Debug, PartialEq, Eq)]
pub enum Error {
/// nom returned an error.
Nom(nom::error::ErrorKind),
/// nom did not return an error, but the EBML is incorrect.
Custom(EbmlError),
}
```
It's fairly self-explanatory, but something to note is that I removed the `input: &'a [u8]` field from the error. The reason for this is that I don't see a big advantage in keeping it. It was actually kind of annoying to get the entire (sometimes >10MiB) input dumped to the terminal.
The `EbmlError` enum now also includes an EBML/Matroska element ID in a lot of cases. This required changing some functions to "pass through" the ID. I hope this isn't a big performance hit, but can always be removed …

Change the EBML error type (again)

---

Cargo.toml
src/ebml.rs
src/elements.rs

I found what made the tests from #106 fail: CRC elements aren't handled in the EBML header.
Changes:
1. Add `parse_binary_exact` to get an exact amount of bytes in an array
2. Add combinator-style functions to get the checksum from the input (`fn crc`) and to verify the data with the checksum (`fn checksum`)
(2.5) Add the `crc` crate to calculate the checksum(s) as per the [specification](https://www.rfc-editor.org/rfc/rfc8794.html#section-11.3.1-1.16).
3. Use these functions in `ebml_header` and `sub_element`
The complete error handling for CRC-32 is a [bit more involved](https://www.rfc-editor.org/rfc/rfc8794.html#name-considerations-for-reading-) than just returning an error, but I'd say it's good enough for now.

Implement CRC-32 elements & verification

---

assets/matroska_test_w1_1/Release.txt
assets/matroska_test_w1_1/test1-tag.xml
assets/matroska_test_w1_1/test2-tag.xml
assets/matroska_test_w1_1/test3-tag.xml
assets/matroska_test_w1_1/test4-tag.xml
assets/matroska_test_w1_1/test5-tag.xml
assets/matroska_test_w1_1/test6-tag.xml
assets/matroska_test_w1_1/test7-tag.xml
assets/matroska_test_w1_1/test8-tag.xml
src/ebml.rs

Not sure how you feel about merging a failing test.
I chose not to use `include_bytes!` in the test because that would've bloated the binary to >150MiB. This just means the test has to run in the project root directory to read the files at runtime.

Add Matroska test suite & basic test

---

Cargo.toml
src/elements.rs
src/serializer/ebml.rs
tools/src/matroska_info.rs

The [uuid docs](https://docs.rs/uuid/1.3.0/uuid/). The `Uuid` struct is basically a thin wrapper around `[u8; 16]` with some helper functions and ways to create different versions of UUIDs.
If creating UUIDs ever gets relevant, the only reference I can find is for the [SegmentUUID element](https://www.ietf.org/archive/id/draft-ietf-cellar-matroska-15.html#name-segmentuuid-element) which states that it is equivalent to a UUID v4.

Introduce `Uuid` type from `uuid` crate for UIDs

---

src/ebml.rs
src/elements.rs
tools/src/matroska_info.rs

Element Sizes are generally VINTs (up to u64), but the `take` combinator, which we use to get the Element data, only accepts `usize` (for good reason).
The `elem_size` helper fn is meant to replace `vint` in places where we know that we're getting the element size. It will do the same thing as before, but immediately convert to `usize` (or error) instead of doing it later via `usize_error`. This makes life easier since we need `usize` for most things anyways, so this saves us some `x as usize` and a bit of boilerplate.

Introduce helper method for Element Sizes

---

src/ebml.rs
src/elements.rs
src/serializer/ebml.rs
tools/src/matroska_info.rs

Closes #110. Mostly signature changes. The `vid_size` function broke so I rewrote it. We can now take advantage of the 4-octet maximum, because the first byte with any bit set to one now signals the size of the ID. Also looks like cookie_factory has some new functions and macros that are a bit more ergonomic than the legacy stuff.

Use u32 for Element IDs instead of u64

---

src/ebml.rs
src/serializer/ebml.rs

Closes #105.
For parsing, there's a new code path that verifies a size of 4 octets or less for these elements.
For serialization, the u32s can just be widened to u64s. The code already handles "downsizing" to the smallest representation, so this is fine from what I can tell.

Change EBML header fields from u64 to u32

---

src/elements.rs
src/muxer.rs
src/serializer/elements.rs
tools/src/matroska_info.rs

Pretty [self-explanatory](https://www.ietf.org/archive/id/draft-ietf-cellar-matroska-16.html#name-seekid-element):
> 5.1.1.1.1 SeekID Element
id / type: 0x53AB / binary
length: 4
path: \Segment\SeekHead\Seek\SeekID
minOccurs / maxOccurs: 1 / 1
definition: The binary EBML ID of a Top-Level Element. 
Since the length is always 4, we can just interpret the bytes as a u32.

SeekID is an EBML ID: `Vec<u8>` -> `u32`

---

src/demuxer.rs
src/elements.rs
src/muxer.rs
src/serializer/elements.rs
tools/src/matroska_info.rs

Timecode is the old, "mistaken" ([their words](https://www.ietf.org/archive/id/draft-ietf-cellar-matroska-16.html#name-timestamps), not mine) name for what is now the Timestamp.

Rename Timecode to Timestamp

---

src/ebml.rs
src/elements.rs
src/permutation.rs

This addresses #117.
1. Permutation now doesn't return a tuple of `(Option<T1>, Option<T2>, ...)` but just `(T1, T2, ...)`. `Option<T>` is now only used if the Element is explicitly optional (for example, by using `opt(uint(id))` instead of just `uint(id)`). This means no more `value_error` helper function, because `fn permutation` now handles "unwrapping".
2. Introduce `check_id` function to replace `verify(vid, |val| *val == id)` that we had in a few places. Except the error is now `Ebml(id, ParseError::MissingElement)`.
3. Override `<ebml::Error as ParseError>::or` to avoid having the `Complete` ErrorKind shadow the real error.
4. Introduce `skip_master` function and use it to skip Elements with unknown IDs (with warn log message)
Overall, this improves readability (explicit `opt` + …

Rework Permutation for better ergonomics & to skip unknown Elements

---

src/ebml/error.rs
src/ebml/parse.rs
src/elements.rs
src/serializer/ebml.rs
src/serializer/elements.rs
tools/Cargo.toml
tools/src/matroska_info.rs

This creates a newtype for EBML dates which is a thin wrapper around an i64 with some special handling for parsing and serialization. Technically, there is an optimization to be done here (see the FIXME), but that should be a pretty rare case.

Implement EBML date element

---

src/ebml/macros.rs
src/elements.rs

Closes #129.
`[x..]` won't work for any x, only `0` and `1` will match in the helper macro so anything else won't even compile. Also, if the entire `[0..]`/`[1..]` is missing, there is no many0/many1, it just tries to parse the `Vec<T>` like a normal EbmlParsable.

Add optional lower_bound to EBML macro

---

src/demuxer.rs

This is one of the big bugs making demuxing/remuxing break. noms `Needed::Size(x)` only gives the amount of **additional** bytes needed, while `MoreDataNeeded` wants the amount of **total** bytes needed.

Fix MoreDataNeeded containing the wrong size

---

.github/workflows/matroska.yml
src/elements.rs

When I used this library to parse SimpleBlock, I found that the parsed keyframe field value was wrong. After querying the rfc document, I found that the parsing was wrong.
In RFC doc: https://datatracker.ietf.org/doc/rfc9559/
10.2.  SimpleBlock Structure says: Bit 0 is the most significant bit.

Fix SimpleBlock header struct parse error
